version: '3.2'

services:
 back:
  build: ./back
  ports:
        - "5500:5500"
  links:
        - mongo
  environment:
        - URL_MONGO=mongodb://api:docker1234@mongo

 mongo:
  image: mongo:4.4.6
  ports:
        - "3000:3000"
  volumes:
        - "./mongo/data:/data/db"
  environment:
        - MONGO_INITDB_ROOT_USERNAME=api
        - MONGO_INITDB_ROOT_PASSWORD=docker1234